from typing import List

DEFAULT_PORT: int = 5678
DEFAULT_HOST: str = "0.0.0.0"

ED_KWDS: List[str] = ["university", "college", "student", "teacher", "professor"]
ED_KWDS_PATTERN: str = f'({"|".join(ED_KWDS)})'

DEFAULT_PUBPORT = 5000
DEFAULT_REPPORT = 6000
DEFAULT_SUBPORT = DEFAULT_PUBPORT
DEFAULT_REQPORT = DEFAULT_REPPORT
V_SRC_PUSH_PORT = 8000
V_SRC_REP_PORT = 8001
V_SRC_REQ_PORT = 8002
V_W_PUSH_PORT = 8003
